# Generated by Django 2.0 on 2020-01-19 15:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hood', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businesses',
            name='name',
            field=models.CharField(max_length=140),
        ),
        migrations.AlterField(
            model_name='healthservices',
            name='logo',
            field=models.ImageField(upload_to='healthlogo/'),
        ),
        migrations.AlterField(
            model_name='healthservices',
            name='name',
            field=models.CharField(max_length=70),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='profile',
            name='picture',
            field=models.ImageField(blank=True, upload_to='profile/'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
