# Generated by Django 2.0 on 2020-01-19 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hood', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='picture',
            field=models.ImageField(blank=True, default='yumy.jpg', null=True, upload_to='profile/'),
        ),
    ]
