# Generated by Django 2.0 on 2020-01-19 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hood', '0002_auto_20200119_1839'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminstration',
            name='contact',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='businesses',
            name='contacts',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='healthservices',
            name='contact',
            field=models.IntegerField(default=0),
        ),
    ]
