# Generated by Django 2.0 on 2020-01-19 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hood', '0004_auto_20200119_1630'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hood',
            name='hood_name',
            field=models.CharField(max_length=60, null=True),
        ),
    ]
