# Generated by Django 2.0 on 2020-01-19 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hood', '0004_auto_20200119_1855'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='picture',
            field=models.ImageField(blank=True, default='yummy.jpg', upload_to='profile/'),
        ),
    ]
